<div class="span12" id="content">

    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Applicants</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Go!</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>List of Applicants</h2>
                        <div class="clearfix"></div>
                    </div>
                    <!-- Content -->
                    <div class="x_content">
                        <div class="clearfix"></div>
                        <div class="row">

                            <?php if (!empty($this->applicants)) { ?>
                                <?php foreach ($this->applicants as $applicant) { ?>
                                    <div class="col-md-4 col-sm-4 col-xs-12 animated fadeInDown">
                                        <div class="well profile_view">
                                            <div class="col-sm-12">
                                                <h4 class="brief"><i>ID #<?php echo $this->escape($applicant->getId()); ?></i></h4>
                                                <div class="left col-xs-7">
                                                    <h2><?php echo $this->escape($applicant->getFirstName()); ?> <?php echo $this->escape($applicant->getLastName()); ?></h2>

                                                    <ul class="list-unstyled">
                                                        <li><?php echo $this->escape($applicant->getSeniority()); ?> Java Developer</li>
                                                        <br/>
                                                        <li><i class="fa fa-home"></i> <?php echo $this->escape($applicant->getCity()); ?></li>
                                                    </ul>
                                                </div>
                                                <div class="right col-xs-5 text-center pull-right">
                                                    <img src="images/img.jpg" alt="" class="img-circle img-responsive">
                                                </div>
                                            </div>
                                            &nbsp;<br/>

                                            <div class="col-xs-12 bottom text-center">
                                                <div class="col-xs-12 col-sm-6 emphasis">
                                                    <p class="ratings">
                                                        <strong>Score:</strong>
                                                        <a>4.0</a>
                                                    </p>
                                                </div>
                                                <div class="col-xs-12 col-sm-6 emphasis">
                                                    <a class="btn pull-right btn-primary btn-xs" href="<?php
                                                    echo $this->url(array(
                                                        'controller' => 'applicant',
                                                        'action' => 'edit',
                                                        'id' => $applicant->getId()), 'default', true)
                                                    ?>"> <i class="fa fa-user">
                                                        </i> View Profile </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>
                            <?php } else { ?>
                                There are no applicants. Start by <a href='<?php
                                echo $this->url(
                                        array('controller' => 'applicant',
                                    'action' => 'edit'), 'default', true)
                                ?>'>creating one</a>.
                                                                 <?php } ?>

                        </div>
                    </div>
                </div>


            </div>
            <!--/Content -->
        </div>


    </div>
</div>                               