<div class="span12" id="content">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Tests</h3>
                	<div class="message"><?php echo $this->messages();?></div>
                <br/>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>List of Tests</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <table id="example" class="table table-striped responsive-utilities jambo_table">
                            <thead>
                                <tr class="headings">
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Created At</th> 
                                    <th>Questions</th>
                                    <th>Test For</th>
                                    <th class="no-link last"><span class="nobr">Action</span>
                                    </th>
                                </tr>
                            </thead>

                            <tbody>
                                <?php foreach ($this->tests as $test) { ?>
                                    <tr>
                                        <td class=""><?php echo $this->escape($test->getId()); ?></td>
                                        <td class=""><?php echo $this->escape($test->getName()); ?></td>
                                        <td class=""><?php echo $this->escape($test->getDescription()); ?></td>
                                        <td class=""><?php echo $this->escape($test->getCreatedAt()); ?></td>
                                        <td class=""><?php echo $this->escape(count($test->getCurrentQuestions())); ?></td>
                                        <td class=""><?php echo $this->escape($test->getTestFor()); ?></td>
                                        <td class=" last">
                                            <a href="<?php
                                            echo $this->url(array(
                                                'controller' => 'test',
                                                'action' => 'detail',
                                                'id' => $test->getId()), 'default', true)
                                            ?>" class="btn btn-primary btn-xs" style="margin: 0px;"><i class="fa fa-info"></i>&nbsp;&nbsp;Detail</a>
                                        </td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    
                </div>
            </div>

        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>