<!DOCTYPE html>
<html lang="en">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title><?php echo $this->title ?> | Interview.me</title>

        <!-- Bootstrap core CSS -->

        <?php
        $this->headLink()->appendStylesheet($this->baseUrl() . '/css/bootstrap.min.css');
        $this->headLink()->appendStylesheet($this->baseUrl() . '/fonts/css/font-awesome.min.css');
        $this->headLink()->appendStylesheet($this->baseUrl() . '/css/animate.min.css');
        $this->headLink()->appendStylesheet($this->baseUrl() . '/css/custom.css');
        $this->headLink()->appendStylesheet($this->baseUrl() . '/css/maps/jquery-jvectormap-2.0.1.css');
        $this->headLink()->appendStylesheet($this->baseUrl() . '/css/icheck/flat/green.css');
        $this->headLink()->appendStylesheet($this->baseUrl() . '/css/floatexamples.css');
        $this->headLink()->appendStylesheet($this->baseUrl() . '/css/prism.css');
        $this->headLink()->appendStylesheet('//code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css');
        $this->headLink()->appendStylesheet('/css/datatables/tools/css/dataTables.tableTools.css');

        echo $this->headLink();

        $this->headScript()->appendFile($this->baseUrl() . '/js/jquery.min.js');
        $this->headScript()->appendFile($this->baseUrl() . '/js/datatables/js/jquery.dataTables.js');
        $this->headScript()->appendFile($this->baseUrl() . '/js/datatables/tools/js/dataTables.tableTools.js');
        $this->headScript()->appendFile($this->baseUrl() . '/js/prism.js');
        $this->headScript()->appendFile('//code.jquery.com/ui/1.11.3/jquery-ui.min.js');

        echo $this->headScript();

        $userNamespace = new Zend_Session_Namespace('User');
        ?>

<!--<script>
    NProgress.start();
</script>-->

        <!--[if lt IE 9]>
            <script src="../assets/js/ie8-responsive-file-warning.js"></script>
            <![endif]-->

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
              <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
              <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
            <![endif]-->

    </head>


    <body class="nav-md">

        <div class="container body">


            <div class="main_container">

                <div class="col-md-3 left_col">
                    <div class="left_col scroll-view">

                        <div class="navbar nav_title" style="border: 0;">
                            <a href="<?php
                            echo $this->url(
                                    array('controller' => 'applicants'), 'default', true)
                            ?>" class="site_title"><img src="<?php echo $this->baseUrl(); ?>/images/interviewme_logo_white.png" 
                                                      alt="Interview.me" 
                                                      style="width:80%;" /></a>
                        </div>
                        <div class="clearfix"></div>

                        <br />

                        <!-- sidebar menu -->
                        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

                            <div class="menu_section">
                                <h3 style="margin-top:20px">Menu</h3>
                                <ul class="nav side-menu">
                                    <li><a href="<?php
                                        echo $this->url(
                                                array('controller' => 'index'), 'default', true)
                                        ?>"><i class="fa fa-home"></i> Dashboard </a>

                                    </li>
                                    <li><a><i class="fa fa-user"></i> Applicants <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu" style="display: none">
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('controller' => 'applicants'), 'default', true)
                                                ?>">List of Applicants</a>
                                            </li>

                                            <?php if (Zend_Registry::get('ACL')->isAllowed(Zend_Registry::get('ROLE'), "applicant", "edit")) { ?>
                                                <li><a href="<?php
                                                    echo $this->url(
                                                            array('controller' => 'applicant',
                                                        'action' => 'edit'), 'default', true)
                                                    ?>">Add New Applicant</a>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                    </li>
                                    <li><a><i class="fa fa-edit"></i> Tests <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu" style="display: none">
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('controller' => 'test'), 'default', true)
                                                ?>">List of Tests</a>
                                            </li>
                                            <li><a href="<?php
                                                echo $this->url(
                                                        array('controller' => 'test',
                                                    'action' => 'edit'), 'default', true)
                                                ?>">Add New Test</a>
                                            </li>
                                        </ul>
                                    </li>

                                    <?php if (Zend_Registry::get('ACL')->isAllowed(Zend_Registry::get('ROLE'), "test")) { ?>
                                        <li><a><i class="fa fa-users"></i> Users <span class="fa fa-chevron-down"></span></a>
                                            <ul class="nav child_menu" style="display: none">
                                                <li><a href="<?php
                                                    echo $this->url(
                                                            array('controller' => 'user'), 'default', true)
                                                    ?>">List of Users</a>
                                                </li>
                                                <li><a href="<?php
                                                    echo $this->url(
                                                            array('controller' => 'user',
                                                        'action' => 'edit'), 'default', true)
                                                    ?>">Add New User</a>
                                                </li>
                                            </ul>
                                        </li>

                                    <?php } ?>
                                </ul>
                            </div>

                        </div>
                        <!-- /sidebar menu -->
                    </div>
                </div>

                <!-- top navigation -->
                <div class="top_nav">

                    <div class="nav_menu">
                        <nav class="" role="navigation">
                            <div class="nav toggle">
                                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                            </div>

                            <ul class="nav navbar-nav navbar-right">
                                <li class="">
                                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">

                                        <img src="<?php
                                        echo $this->url(array(
                                            'controller' => 'user',
                                            'action' => 'photo',
                                            'id' => $userNamespace->user->getId()), 'default', true)
                                        ?>" alt="" />

                                        <?php
                                        echo $userNamespace->user->getFullName();
                                        echo " (" . Zend_Registry::get('ROLE') . ")";
                                        ?>
                                        <span class=" fa fa-angle-down"></span>
                                    </a>
                                    <ul class="dropdown-menu dropdown-usermenu animated fadeInDown pull-right">
                                        <?php if (Zend_Registry::get('ACL')->isAllowed(Zend_Registry::get('ROLE'), "user", "detail")) { ?>
                                            <li><a href="<?php
                                                echo $this->url(array(
                                                    'controller' => 'user',
                                                    'action' => 'detail',
                                                    'id' => $userNamespace->user->getId()), 'default', true)
                                                ?>"><i class="fa fa-user pull-right"></i> User Profile</a>
                                            </li>
                                        <?php } ?>
                                        <li><a href="<?php
                                            echo $this->url(
                                                    array('controller' => 'admin',
                                                'action' => 'logout',), 'default', true)
                                            ?>"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                                        </li>
                                    </ul>
                                </li>

                            </ul>
                        </nav>
                    </div>

                </div>
                <!-- /top navigation -->

                <!-- page content -->
                <div class="right_col" role="main">

                <div class="message"><?php echo $this->messages(); ?></div>
                    <?php echo $this->layout()->content ?>

                    <!-- footer content -->

                    <footer>
                        <div class="">
                            <p class="pull-right">&copy; 2015 Tým 3 |
                                <span class="lead"> Interview.me</span>
                            </p>
                        </div>
                        <div class="clearfix"></div>
                    </footer>
                    <!-- /footer content -->
                </div>
                <!-- /page content -->

            </div>

        </div>

        <div id="custom_notifications" class="custom-notifications dsp_none">
            <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
            </ul>
            <div class="clearfix"></div>
            <div id="notif-group" class="tabbed_notifications"></div>
        </div>

        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap.min.js"></script>

        <!-- bootstrap progress js -->
        <script src="<?php echo $this->baseUrl(); ?>/js/progressbar/bootstrap-progressbar.min.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/nicescroll/jquery.nicescroll.min.js"></script>
        <!-- icheck -->
        <script src="<?php echo $this->baseUrl(); ?>/js/icheck/icheck.min.js"></script>
        <!-- daterangepicker -->
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/moment.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/datepicker/daterangepicker.js"></script>

        <script src="<?php echo $this->baseUrl(); ?>/js/chartjs/chart.min.js"></script>

        <script src="<?php echo $this->baseUrl(); ?>/js/custom.js"></script>
        <!--
                <script>
                    $(document).ready(function () {
                        /* assuming that text input datePicker would have id='datePicker' */
                        $(".datePicker").datepicker({dateFormat: 'dd/mm/yy'});
                                
                 });
                </script>
        -->
    </body>

</html>
