<!DOCTYPE html>
<html lang="en">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Log In | InterviewMe</title>

        <!-- Bootstrap core CSS -->

        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/bootstrap.min.css'); ?>

        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/fonts/css/font-awesome.min.css'); ?>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/animate.min.css'); ?>

        <!-- Custom styling plus plugins -->
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/custom.css'); ?>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/icheck/flat/green.css'); ?>


        <?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/jquery.min.js'); ?>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
              <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
              <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
            <![endif]-->

    </head>

    <body style="background:#F7F7F7;">

        <div class="container">
            <div id="wrapper">
                <div id="login" class="animate form">
                    <section class="login_content">
                        <div class="form">
                            <img src="<?php echo $this->baseUrl();?>/images/interviewme_logo.png" 
                                 alt="Interview.me" 
                                 style="width:80%; margin-bottom:-30px"/>
                                 <?php echo $this->layout()->content ?>

                            <div class="clearfix"></div>
                            <div class="separator">
                                <div class="clearfix"></div>
                                <br />
                                <div>
                                    <p>&copy; 2015 Tým 3 | Interview.me</p>
                                </div>
                            </div>
                        </div>
                    </section>
                    <!-- content -->
                </div>
            </div>
        </div>

    </body>

</html>