<div class="span12" id="content">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3><?php
                    echo $this->escape($this->user->getUsername())." (".$this->escape($this->user->getFullName()).")";
                    ?></h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <form style="margin: 0; padding: 0; display:inline;" action="<?php
                echo $this->url(
                        array('controller' => 'user',
                    'action' => 'delete',
                    'id' => $this->user->getId()), 'default', true)
                ?>" method="post">

                    <a href="<?php
                    echo $this->url(
                            array('controller' => 'user'), 'default', true)
                    ?>" class="btn btn-default"><i class="fa fa-arrow-left"></i>&nbsp;Back</a>

                    <a href="<?php
                    echo $this->url(array(
                        'controller' => 'user',
                        'action' => 'edit',
                        'id' => $this->user->getId()), 'default', true)
                    ?>" class="btn btn-primary"><i class="fa fa-edit "></i>&nbsp;Edit</a>

                    <button  type="submit" class="btn btn-danger" 
                             onclick="return confirm('Do you really want to delete this user? \nRelations to interviewed_by in applicants profile will be lost')" >
                        <i class="fa fa-remove" title="Delete"></i>&nbsp;Delete</button></form>
            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-md-6 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Basic Information</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <div class="form-horizontal">

                            <div class="form-group">
                                <label class="col-md-3 col-sm-3 col-xs-12">First Name</label>
                                <div class="col-md-9 col-sm-9 col-xs-12"><?php echo $this->escape($this->user->getFirstName()); ?></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 col-sm-3 col-xs-12">Last Name</label>
                                <div class="col-md-9 col-sm-9 col-xs-12"><?php echo $this->escape($this->user->getLastName()); ?></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 col-sm-3 col-xs-12">Username</label>
                                <div class="col-md-9 col-sm-9 col-xs-12"><?php echo $this->escape($this->user->getUsername()); ?></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 col-sm-3 col-xs-12">Role</label>
                                <div class="col-md-9 col-sm-9 col-xs-12"><?php echo $this->escape($this->user->getRole()); ?></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 col-sm-3 col-xs-12">Last Login</label>
                                <div class="col-md-9 col-sm-9 col-xs-12"><?php echo $this->escape($this->user->getLastLogin()); ?></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 col-sm-3 col-xs-12">IP</label>
                                <div class="col-md-9 col-sm-9 col-xs-12"><?php echo $this->escape($this->user->getIp()); ?></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 col-sm-3 col-xs-12">Browser</label>
                                <div class="col-md-9 col-sm-9 col-xs-12"><?php echo $this->escape($this->user->getBrowser()); ?></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 col-sm-3 col-xs-12">Number of Logins</label>
                                <div class="col-md-9 col-sm-9 col-xs-12"><?php echo $this->escape($this->user->getlognum()); ?></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 col-sm-3 col-xs-12">Created At</label>
                                <div class="col-md-9 col-sm-9 col-xs-12"><?php echo $this->escape($this->user->getCreatedAt()); ?></div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 col-sm-3 col-xs-12">Last Modified At</label>
                                <div class="col-md-9 col-sm-9 col-xs-12"><?php echo $this->escape($this->user->getLastModifiedAt()); ?></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Additional Information</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="form-group">
                            <label class="col-md-3 col-sm-3 col-xs-12">Photo</label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <img style="max-height:200px; width:auto;" src="<?php
                                     echo $this->url(array(
                                         'controller' => 'user',
                                         'action' => 'photo',
                                         'id' => $this->user->getId()), 'default', true)
                                     ?>" alt="<?php echo $this->user->getFullName(); ?>" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

      
            



<script>
    $(document).ready(function () {
        var oTable = $('#tests').dataTable({
            "aaSorting": [[0, 'desc']],
            "oLanguage": {
                "sSearch": "Search all columns:"
            },
            "aoColumnDefs": [
                {
                    'bSortable': false,
                    'aTargets': [7]
                } //disables sorting for the last column (Action)
            ],
            'iDisplayLength': 12,
            "sPaginationType": "full_numbers",
        });
        $("tfoot input").keyup(function () {
            /* Filter on the column based on the index of this element's parent <th> */
            oTable.fnFilter(this.value, $("tfoot th").index($(this).parent()));
        });
        $("tfoot input").each(function (i) {
            asInitVals[i] = this.value;
        });
        $("tfoot input").focus(function () {
            if (this.className == "search_init") {
                this.className = "";
                this.value = "";
            }
        });
        $("tfoot input").blur(function (i) {
            if (this.value == "") {
                this.className = "search_init";
                this.value = asInitVals[$("tfoot input").index(this)];
            }
        });
    });
</script>