<div class="row">

    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Questions for <?php echo $this->escape($this->test->getName()); ?>

                </h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a href="<?php
                        echo $this->url(array(
                            'controller' => 'testquestion',
                            'action' => 'addtestquestion',
                            'id' => $this->testId,
                                ), 'default', true);
                        ?>" class="btn btn-success btn-xs" style="margin: 0px;background-color:#26b99a"><i class="fa fa-plus"></i>Add question</a></li>
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <table class="table" id="example">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Type</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->questions as $question) {
                            ?>
                            <tr>
                                <th scope="row"><?php echo $question->getId(); ?></th>
                                <td><?php echo $this->escape($question->getName()); ?></td>
                                <td><?php echo $this->escape($question->getType()); ?></td>
                                <td><a href="<?php
                                    echo $this->url(array(
                                        'controller' => 'testquestion',
                                        'action' => 'edittestquestion',
                                        'id' => $question->getId(),
                                    'test_id' => $this->testId), 'default', true);
                                    ?>"><i class="fa fa-pencil" title="Edit"></i></a>
                                    | 

                                    <form style="margin: 0; padding: 0; display:inline;" action="<?php
                                    echo $this->url(
                                    array('controller' => 'testquestion',
                                    'action' => 'deletetestquestion',
                                    'id' => $question->getId(),
                                    'test_id' => $this->testId
                                    ), 'default', true)
                                    ?>" method="post">
                                        <button style="margin: 0; padding: 0;" type="submit" class="btn btn-link" 
                                                onclick="return confirm('Do you really want to delete question <?php echo $this->escape($question->getName()); ?>?')" >
                                            <i class="fa fa-remove" title="Delete"></i></button></form>
                                </td>
                            </tr>

<?php } ?>

                    </tbody>
                </table>

            </div>
        </div>
    </div>


</div>

<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>